name: rllab3
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.5.2
    - numpy==1.12.0
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako
    - ipywidgets
    - flask
    - pybox2d
    - pygame
    - matplotlib
    - pandas
    - mkl-service
    - pip:
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - cached_property
        - cloudpickle
        - git+https://github.com/Lasagne/Lasagne.git#egg=Lasagne
        - git+https://github.com/Theano/Theano.git#egg=Theano
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - git+https://github.com/deepmind/dm_control.git#egg=dm_control
        - awscli
        - git+https://github.com/openai/gym.git@v0.7.4#egg=gym
        - pyglet
        - jupyter
        - hyperopt
        - polling
        - tensorboard
